Demo Using Docker Env
frontegg/php-sdk pull request #10
Opened 2020-08-26 08:26 UTC by nuzzy

* Created demo environment with docker for raw PHP.

2020-08-26 11:42 UTC, aviadmizrachi requested changes

2020-08-26 11:42 UTC, aviadmizrachi commented on docker/index.php
> +$clientId = '6da27373-1572-444f-b3c5-ef702ce65123';
No secrets in code please

2020-08-26 12:52 UTC, nuzzy commented on docker/index.php
> +$clientId = '6da27373-1572-444f-b3c5-ef702ce65123';
Fixed

2020-08-31 13:11 UTC, aviadmizrachi approved these changes

2020-08-31 13:11 UTC, merged